# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mediaApp_A01197705' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod "youtube-ios-player-helper", "~> 1.0.4"

end
